settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: cocoNUT
  path: .
  commands:
    install:
      status: true
      method: go build -o ./coconut
    run:
      status: true
      method: ./coconut
  watcher:
    extensions:
    - go
    paths:
    - ./
    ignored_paths:
    - frontend/node_modules
    - .git
    - .realize
    - vendor
