version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: coconut_production
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  ruby:
    image: ruby:2.5
    command: bash -c 'gem install pg && gem install standalone_migrations && rake db:migrate RAILS_ENV=production'
    working_dir: /ruby_db/
    volumes:
      - ./:/ruby_db/
      - ./config/conf.docker.yml:/ruby_db/config/conf.yml
  gin:
    build: .
    restart: always
    depends_on:
      - "db"
    ports:
      - "9876:9876"