version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: coconut_production
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  gin:
    build: .
    restart: always
    depends_on:
      - "db"
    ports:
      - "9876:9876"