development:
  adapter: postgresql
  database: coconut_development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  database: coconut_test
  pool: 5
  port: 5432
  host: localhost
